[params]
author="Alfred Nutile"
authorImgPath = "/img/author.jpg"
authorBlurb = "Director, Developer, Technology Enthusiast"

[taxonomies]
  tag = "tags"

[social]
  email = "me@alfrednutile.info"
  twitter = "https://twitter.com/alnutile"
  medium = "https://medium.com/@alnutile"
  github = "https://twitter.com/alnutile"
  linkedin = "https://www.linkedin.com/in/alfrednutile/"



disqusShortname="alfrednutile"

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"

